In [41]:
import numpy as np

In [42]:
arr01 = np.array([1,2,3,4,5])
print(arr01)

[1 2 3 4 5]


In [43]:
arr02 = np.array([1,2,3,4,'Sunil'])
print(arr02)

['1' '2' '3' '4' 'Sunil']


In [44]:
arr03 = np.array([1,2,3,4,1.0,3.0], dtype=int)
print(arr03)

[1 2 3 4 1 3]


In [45]:
arr04 = np.array([1,2,3,4,'Sunil','Arun'], dtype=object)
print(arr04)

[1 2 3 4 'Sunil' 'Arun']


In [46]:
a = np.array([10,20,30,40,50])
print(f'1st item: {a[0]}')
print(f'2nd item: {a[1]}')
print(f'3rd item: {a[2]}')
print(f'4th item: {a[3]}')

1st item: 10
2nd item: 20
3rd item: 30
4th item: 40


In [47]:
arr_2d = np.array([
    [11,12,13],
    [14,15,16],
    [17,18,19]
])
print(f'{arr_2d[0,0]}')
print(f'{arr_2d[0,1]}')
print(f'{arr_2d[0,2]}')
print(f'{arr_2d[1,0]}')
print(f'{arr_2d[1,1]}')
print(f'{arr_2d[1,2]}')
print(f'{arr_2d[2,0]}')
print(f'{arr_2d[2,1]}')
print(f'{arr_2d[2,2]}')

11
12
13
14
15
16
17
18
19


In [48]:
arr6 = np.array([10,20,30,40,50,60,70])
arr6_slice = arr6[1:5]
print(arr6_slice)

[20 30 40 50]


In [49]:
arr6[4:]

array([50, 60, 70])

In [50]:
arr6[::1]

array([10, 20, 30, 40, 50, 60, 70])

In [51]:
arr6[::2]

array([10, 30, 50, 70])

In [52]:
arr6[-3:-1]

array([50, 60])

In [53]:
arr6[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [54]:
arr7 = np.array(['Sunil','Ghimire','Sishir','Kathmandu'])
arr7[::-1]

array(['Kathmandu', 'Sishir', 'Ghimire', 'Sunil'], dtype='<U9')

In [55]:
arr7[::-2]

array(['Kathmandu', 'Ghimire'], dtype='<U9')

In [56]:
arr7[::2]

array(['Sunil', 'Sishir'], dtype='<U9')

In [57]:
arr7 = np.array([
    [11,12,13],
    [14,15,16],
    [17,18,19]
])

In [58]:
arr7[1,1:]

array([15, 16])

In [59]:
arr7[2,1:3]

array([18, 19])

In [60]:
base_arr = np.array([10,20,30,40,50,60])
print(base_arr)

[10 20 30 40 50 60]


In [61]:
base_arr.copy()

array([10, 20, 30, 40, 50, 60])

In [62]:
base_copy = base_arr.copy()
print(base_copy)

[10 20 30 40 50 60]


In [63]:
copy_arr = base_arr
print(copy_arr)

[10 20 30 40 50 60]


In [64]:
print(f'''Do original array and copy array share a memory?'
     Ans:{np.shares_memory(base_arr, copy_arr)}''')

Do original array and copy array share a memory?'
     Ans:True
