In [1]:
import numpy as np

In [2]:
arr01 = np.array([1,2,3,4,5])
print(arr01)

[1 2 3 4 5]


In [3]:
arr02 = np.array([1,2,3,4,'Sunil'])
print(arr02)

['1' '2' '3' '4' 'Sunil']


In [7]:
arr03 = np.array([1,2,3,4,1.0,3.0], dtype=int)
print(arr03)

[1 2 3 4 1 3]


In [9]:
arr04 = np.array([1,2,3,4,'Sunil','Arun'], dtype=object)
print(arr04)

[1 2 3 4 'Sunil' 'Arun']


In [11]:
a = np.array([10,20,30,40,50])
print(f'1st item: {a[0]}')
print(f'2nd item: {a[1]}')
print(f'3rd item: {a[2]}')
print(f'4th item: {a[3]}')

1st item: 10
2nd item: 20
3rd item: 30
4th item: 40


In [14]:
arr_2d = np.array([
    [11,12,13],
    [14,15,16],
    [17,18,19]
])
print(f'{arr_2d[0,0]}')
print(f'{arr_2d[0,1]}')
print(f'{arr_2d[0,2]}')
print(f'{arr_2d[1,0]}')
print(f'{arr_2d[1,1]}')
print(f'{arr_2d[1,2]}')
print(f'{arr_2d[2,0]}')
print(f'{arr_2d[2,1]}')
print(f'{arr_2d[2,2]}')

11
12
13
14
15
16
17
18
19


In [16]:
arr6 = np.array([10,20,30,40,50,60,70])
arr6_slice = arr6[1:5]
print(arr6_slice)

[20 30 40 50]


In [17]:
arr6[4:]

array([50, 60, 70])

In [23]:
arr6[::1]

array([10, 20, 30, 40, 50, 60, 70])

In [24]:
arr6[::2]

array([10, 30, 50, 70])

In [25]:
arr6[-3:-1]

array([50, 60])

In [26]:
arr6[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [ ]:
arr6 = np.array(['Sun'])