In [1]:
import numpy as np

In [9]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [16]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [23]:
arr1.max()

9

In [24]:
arr1.argmax() #index location of max value

8

In [25]:
arr1.max(axis = 0) #max of column using axis=0

array([7, 8, 9])

In [26]:
arr1.max(axis=1) #max of row using axis=1

array([3, 6, 9])

In [31]:
arr2.min()

1

In [32]:
arr2.argmin()

0

In [33]:
arr2.min(axis=0)

array([1, 2, 3])

In [34]:
arr2.min(axis=1)

array([1, 4, 7])

In [35]:
np.sum(arr1)

45

In [36]:
np.sum(arr1, axis=0)

array([12, 15, 18])

In [37]:
np.sum(arr1, axis=1)

array([ 6, 15, 24])

In [38]:
arr2.mean() #avergae of matrix

5.0

In [40]:
np.mean(arr1) #average of matrix

5.0

In [42]:
np.sqrt(arr1)  #square root of each elements

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [43]:
np.std(arr1)  #standard deviation of arr1

2.581988897471611

In [45]:
np.exp(arr1)  #exponential of each element of matrix

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [47]:
np.log(arr1)  #log of each element of matrix

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [49]:
np.log10(arr1) #log based 10 of each elements of matrix

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [50]:
np.concatenate((arr1,arr2)) #by default it is in column wise concatinate

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.concatenate((arr1, arr2), axis=1) #row wise concatinate

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [56]:
np.vstack((arr1, arr2)) #vertical wise concatinate

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.hstack((arr1, arr2)) #horizontal wise concatinate

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [66]:
arr3 = np.arange(1,17).reshape(4,4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
np.split(arr3,2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [70]:
d1 = np.array([4,5,6,7,8,9])
d1

array([4, 5, 6, 7, 8, 9])

In [74]:
 np.split(d1, [1,3])

[array([4]), array([5, 6]), array([7, 8, 9])]