In [5]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [6]:
data_path = 'automobileEDA.csv'
df = pd.read_csv(data_path)
df

symboling  normalized-losses         make aspiration num-of-doors  \
0            3                122  alfa-romero        std          two   
1            3                122  alfa-romero        std          two   
2            1                122  alfa-romero        std          two   
3            2                164         audi        std         four   
4            2                164         audi        std         four   
..         ...                ...          ...        ...          ...   
196         -1                 95        volvo        std         four   
197         -1                 95        volvo      turbo         four   
198         -1                 95        volvo        std         four   
199         -1                 95        volvo      turbo         four   
200         -1                 95        volvo      turbo         four   

      body-style drive-wheels engine-location  wheel-base    length  ...  \
0    convertible          rwd           front        88.6  0.811148  ...   
1    convertible          rwd           front        88.6  0.811148  ...   
2      hatchback          rwd           front        94.5  0.822681  ...   
3          sedan          fwd           front        99.8  0.848630  ...   
4          sedan          4wd           front        99.4  0.848630  ...   
..           ...          ...             ...         ...       ...  ...   
196        sedan          rwd           front       109.1  0.907256  ...   
197        sedan          rwd           front       109.1  0.907256  ...   
198        sedan          rwd           front       109.1  0.907256  ...   
199        sedan          rwd           front       109.1  0.907256  ...   
200        sedan          rwd           front       109.1  0.907256  ...   

     compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                  9.0       111.0    5000.0       21          27  13495.0   
1                  9.0       111.0    5000.0       21          27  16500.0   
2                  9.0       154.0    5000.0       19          26  16500.0   
3                 10.0       102.0    5500.0       24          30  13950.0   
4                  8.0       115.0    5500.0       18          22  17450.0   
..                 ...         ...       ...      ...         ...      ...   
196                9.5       114.0    5400.0       23          28  16845.0   
197                8.7       160.0    5300.0       19          25  19045.0   
198                8.8       134.0    5500.0       18          23  21485.0   
199               23.0       106.0    4800.0       26          27  22470.0   
200                9.5       114.0    5400.0       19          25  22625.0   

    city-L/100km  horsepower-binned  diesel  gas  
0      11.190476             Medium       0    1  
1      11.190476             Medium       0    1  
2      12.368421             Medium       0    1  
3       9.791667             Medium       0    1  
4      13.055556             Medium       0    1  
..           ...                ...     ...  ...  
196    10.217391             Medium       0    1  
197    12.368421               High       0    1  
198    13.055556             Medium       0    1  
199     9.038462             Medium       1    0  
200    12.368421             Medium       0    1  

[201 rows x 29 columns]

In [7]:
x = df.drop('price', axis=1)
y = df['price']

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [9]:
X_train_simple = X_train['highway-mpg'].values.reshape(-1,1)
X_test_simple = X_test['highway-mpg'].values.reshape(-1,1)

In [10]:
simple_lm = LinearRegression()
simple_lm.fit(X_train_simple, Y_train)

LinearRegression()

In [11]:
y_hat_simple = simple_lm.predict(X_test_simple)

In [12]:
y_hat_simple[:5]

array([10530.19044542,  7150.17926639, 12220.19603494, 10530.19044542,
       13910.20162445])

In [13]:
simple_lm.intercept_

39260.28546717645

In [14]:
simple_lm.coef_.item()

-845.0027947574558

In [15]:
#For engine_size
df.columns

Index(['symboling', 'normalized-losses', 'make', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price',
       'city-L/100km', 'horsepower-binned', 'diesel', 'gas'],
      dtype='object')

In [16]:
x = df.drop('price', axis=1)
y = df['price']

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [18]:
X_train_simple = X_train['engine-size'].values.reshape(-1,1)
X_test_simple = X_test['engine-size'].values.reshape(-1,1)

In [19]:
simple_lm = LinearRegression()
simple_lm.fit(X_train_simple, Y_train)

LinearRegression()

In [20]:
y_hat_simple = simple_lm.predict(X_test_simple)

In [21]:
y_hat_simple[:5]

array([12200.90004806,  7203.38742473, 12534.06755628,  7536.55493295,
       16532.07765495])

In [22]:
simple_lm.intercept_

-7789.150445273459

In [23]:
simple_lm.coef_.item()

166.58375411113175

In [24]:
#For horsepower
x = df.drop('price', axis=1)
y = df['price']

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [26]:
X_train_simple = X_train['horsepower'].values.reshape(-1,1)
X_test_simple = X_test['horsepower'].values.reshape(-1,1)

In [27]:
simple_lm = LinearRegression()
simple_lm.fit(X_train_simple, Y_train)

LinearRegression()

In [28]:
y_hat_simple = simple_lm.predict(X_test_simple)

In [29]:
y_hat_simple[:5]

array([12166.10030237,  7173.74640389,  9928.14855478,  8550.94747933,
       15436.95285656])

In [30]:
simple_lm.intercept_

-4532.462737395461

In [31]:
simple_lm.coef_.item()

172.15013443062284

In [32]:
to_select = ['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']
X_train_mult = X_train[to_select].values
X_test_mult = X_test[to_select].values

In [33]:
multi_lm = LinearRegression()
multi_lm.fit(X_train_mult, Y_train)

LinearRegression()

In [34]:
y_hat_simple = simple_lm.predict(X_test_simple)

In [35]:
y_hat_simple[:5]

array([12166.10030237,  7173.74640389,  9928.14855478,  8550.94747933,
       15436.95285656])

In [36]:
simple_lm.intercept_

-4532.462737395461

In [37]:
simple_lm.coef_.item()

172.15013443062284

In [39]:
to_select = ['horsepower', 'curb-weight', 'engine-size','highway-mpg']
X_train_mult = X_train[to_select].values
X_test_mult = X_test[to_select].values

In [40]:
multi_lm = LinearRegression()
multi_lm.fit(X_train_mult, Y_train)

LinearRegression()

In [41]:
y_hat_simple = multi_lm.predict(X_test_mult)

In [42]:
y_hat_simple[:5]

array([11457.56050541,  5966.17033563, 11313.13362185,  6839.1134896 ,
       15765.36249767])

In [43]:
multi_lm.intercept_

-11539.108515802094

In [44]:
multi_lm.coef_

array([ 54.23019834,   3.1154028 ,  93.34038826, -18.71070774])

In [45]:
r2_score(Y_test, y_hat_simple)

0.7429274527307541